import 'package:flutter/material.dart';

class Country {
  final int id;
  final String title, description;

  Country({
    required this.id,
    required this.title,
    required this.description,
  });
}

// Our demo Products

List<Country> CountryList = [
  Country(id:1, title:'AF', description:'Afghanistan'),
  Country(id:2, title:'AX', description: 'Åland Islands'),
  Country(id:3, title: 'AL', description:'Albania'),
  Country(id:4, title: 'DZ', description:'Algeria'),
  Country(id:5, title: 'AS', description:'American Samoa'),
  Country(id:6, title: 'AD', description:'Andorra'),
  Country(id:7, title: 'AO', description:'Angola'),
  Country(id:8, title: 'AI', description:'Anguilla'),
  Country(id:9, title: 'AQ', description:'Antarctica'),
  Country(id:10, title: 'AG', description:'Antigua & Barbuda'),
  Country(id:11, title: 'AR', description:'Argentina'),
  Country(id:12, title: 'AM', description:'Armenia'),
  Country(id:13, title: 'AW', description:'Aruba'),
  Country(id:14, title: 'AC', description:'Ascension Island'),
  Country(id:15, title: 'AU', description:'Australia'),
  Country(id:16, title: 'AT', description:'Austria'),
  Country(id:17, title: 'AZ', description:'Azerbaijan'),
  Country(id:18, title: 'BS', description: 'Bahamas'),
  Country(id:19, title: 'BH', description: 'Bahrain'),
  Country(id:20, title: 'BD', description: 'Bangladesh'),
  Country(id:21, title: 'BB', description: 'Barbados'),
  Country(id:22, title: 'BY', description: 'Belarus'),
  Country(id:23, title: 'BE', description: 'Belgium'),
  Country(id:24, title: 'BZ', description: 'Belize'),
  Country(id:25, title: 'BJ', description: 'Benin'),
  Country(id:26, title: 'BM', description: 'Bermuda'),
  Country(id:27, title: 'BT', description: 'Bhutan'),
  Country(id:28, title: 'BO', description: 'Bolivia'),
  Country(id:29, title: 'BA', description: 'Bosnia & Herzegovina'),
  Country(id:30, title: 'BW', description: 'Botswana'),
  Country(id:31, title: 'BR', description: 'Brazil'),
  Country(id:32, title: 'IO', description: 'British Indian Ocean Territory'),
  Country(id:33, title: 'VG', description: 'British Virgin Islands'),
  Country(id:34, title: 'BN', description: 'Brunei'),
  Country(id:35, title: 'BG', description: 'Bulgaria'),
  Country(id:36, title: 'BF', description: 'Burkina Faso'),
  Country(id:37, title: 'BI', description: 'Burundi'),
  Country(id:38, title: 'KH', description: 'Cambodia'),
  Country(id:39, title: 'CM', description: 'Cameroon'),
  Country(id:40, title: 'CA', description: 'Canada'),
  Country(id:41, title: 'IC', description: 'Canary Islands'),
  Country(id:42, title: 'CV', description: 'Cape Verde'),
  Country(id:43, title: 'BQ', description: 'Caribbean Netherlands'),
  Country(id:44, title: 'KY', description: 'Cayman Islands'),
  Country(id:45, title: 'CF', description: 'Central African Republic'),
  Country(id:46, title: 'EA', description: 'Ceuta & Melilla'),
  Country(id:47, title: 'TD', description: 'Chad'),
  Country(id:48, title: 'CL', description: 'Chile'),
  Country(id:49, title: 'CN', description: 'China'),
  Country(id:50, title: 'CX', description: 'Christmas Island'),
  Country(id:51, title: 'CC', description: 'Cocos (Keeling) Islands'),
  Country(id:52, title: 'CO', description: 'Colombia'),
  Country(id:53, title: 'KM', description: 'Comoros'),
  Country(id:54, title: 'CG', description: 'Congo - Brazzaville'),
  Country(id:55, title: 'CD', description: 'Congo - Kinshasa'),
  Country(id:56, title: 'CK', description: 'Cook Islands'),
  Country(id:57, title: 'CR', description: 'Costa Rica'),
  Country(id:58, title: 'CI', description: 'Côte d’Ivoire'),
  Country(id:59, title: 'HR', description: 'Croatia'),
  Country(id:60, title: 'CU', description: 'Cuba'),
  Country(id:61, title: 'CW', description: 'Curaçao'),
  Country(id:62, title: 'CY', description: 'Cyprus'),
  Country(id:63, title: 'CZ', description: 'Czechia'),
  Country(id:64, title: 'DK', description: 'Denmark'),
  Country(id:65, title: 'DG', description: 'Diego Garcia'),
  Country(id:66, title: 'DJ', description: 'Djibouti'),
  Country(id:67, title: 'DM', description: 'Dominica'),
  Country(id:68, title: 'DO', description: 'Dominican Republic'),
  Country(id:69, title: 'EC', description: 'Ecuador'),
  Country(id:70, title: 'EG', description: 'Egypt'),
  Country(id:71, title: 'SV', description: 'El Salvador'),
  Country(id:72, title: 'GQ', description: 'Equatorial Guinea'),
  Country(id:73, title: 'ER', description: 'Eritrea'),
  Country(id:74, title: 'EE', description: 'Estonia'),
  Country(id:75, title: 'ET', description: 'Ethiopia'),
  Country(id:76, title: 'EZ', description: 'Eurozone'),
  Country(id:77, title: 'FK', description: 'Falkland Islands'),
  Country(id:78, title: 'FO', description: 'Faroe Islands'),
  Country(id:79, title: 'FJ', description: 'Fiji'),
  Country(id:80, title: 'FI', description: 'Finland'),
  Country(id:81, title: 'FR', description: 'France'),
  Country(id:82, title: 'GF', description: 'French Guiana'),
  Country(id:83, title: 'PF', description: 'French Polynesia'),
  Country(id:84, title: 'TF', description: 'French Southern Territories'),
  Country(id:85, title: 'GA', description: 'Gabon'),
  Country(id:86, title: 'GM', description: 'Gambia'),
  Country(id:87, title: 'GE', description: 'Georgia'),
  Country(id:88, title: 'DE', description: 'Germany'),
  Country(id:89, title: 'GH', description: 'Ghana'),
  Country(id:90, title: 'GI', description: 'Gibraltar'),
  Country(id:91, title: 'GR', description: 'Greece'),
  Country(id:92, title: 'GL', description: 'Greenland'),
  Country(id:93, title: 'GD', description: 'Grenada'),
  Country(id:94, title: 'GP', description: 'Guadeloupe'),
  Country(id:95, title: 'GU', description: 'Guam'),
  Country(id:96, title: 'GT', description: 'Guatemala'),
  Country(id:97, title: 'GG', description: 'Guernsey'),
  Country(id:98, title: 'GN', description: 'Guinea'),
  Country(id:99, title: 'GW', description: 'Guinea-Bissau'),
  Country(id:100, title: 'GY', description: 'Guyana'),
  Country(id:101, title: 'HT', description: 'Haiti'),
  Country(id:102, title: 'HN', description: 'Honduras'),
  Country(id:103, title: 'HK', description: 'Hong Kong SAR China'),
  Country(id:104, title: 'HU', description: 'Hungary'),
  Country(id:105, title: 'IS', description: 'Iceland'),
  Country(id:106, title: 'IN', description: 'India'),
  Country(id:107, title: 'ID', description: 'Indonesia'),
  Country(id:108, title: 'IR', description: 'Iran'),
  Country(id:109, title: 'IQ', description: 'Iraq'),
  Country(id:110, title: 'IE', description: 'Ireland'),
  Country(id:111, title: 'IM', description: 'Isle of Man'),
  Country(id:112, title: 'IL', description: 'Israel'),
  Country(id:113, title: 'IT', description: 'Italy'),
  Country(id:114, title: 'JM', description: 'Jamaica'),
  Country(id:115, title: 'JP', description: 'Japan'),
  Country(id:116, title: 'JE', description: 'Jersey'),
  Country(id:117, title: 'JO', description: 'Jordan'),
  Country(id:118, title: 'KZ', description: 'Kazakhstan'),
  Country(id:119, title: 'KE', description: 'Kenya'),
  Country(id:120, title: 'KI', description: 'Kiribati'),
  Country(id:121, title: 'XK', description: 'Kosovo'),
  Country(id:122, title: 'KW', description: 'Kuwait'),
  Country(id:123, title: 'KG', description: 'Kyrgyzstan'),
  Country(id:124, title: 'LA', description: 'Laos'),
  Country(id:125, title: 'LV', description: 'Latvia'),
  Country(id:126, title: 'LB', description: 'Lebanon'),
  Country(id:127, title: 'LS', description: 'Lesotho'),
  Country(id:128, title: 'LR', description: 'Liberia'),
  Country(id:129, title: 'LY', description: 'Libya'),
  Country(id:130, title: 'LI', description: 'Liechtenstein'),
  Country(id:131, title: 'LT', description: 'Lithuania'),
  Country(id:132, title: 'LU', description: 'Luxembourg'),
  Country(id:133, title: 'MO', description: 'Macau SAR China'),
  Country(id:134, title: 'MK', description: 'Macedonia'),
  Country(id:135, title: 'MG', description: 'Madagascar'),
  Country(id:136, title: 'MW', description: 'Malawi'),
  Country(id:137, title: 'MY', description: 'Malaysia'),
  Country(id:138, title: 'MV', description: 'Maldives'),
  Country(id:139, title: 'ML', description: 'Mali'),
  Country(id:140, title: 'MT', description: 'Malta'),
  Country(id:141, title: 'MH', description: 'Marshall Islands'),
  Country(id:142, title: 'MQ', description: 'Martinique'),
  Country(id:143, title: 'MR', description: 'Mauritania'),
  Country(id:144, title: 'MU', description: 'Mauritius'),
  Country(id:145, title: 'YT', description: 'Mayotte'),
  Country(id:146, title: 'MX', description: 'Mexico'),
  Country(id:147, title: 'FM', description: 'Micronesia'),
  Country(id:148, title: 'MD', description: 'Moldova'),
  Country(id:149, title: 'MC', description: 'Monaco'),
  Country(id:150, title: 'MN', description: 'Mongolia'),
  Country(id:151, title: 'ME', description: 'Montenegro'),
  Country(id:152, title: 'MS', description: 'Montserrat'),
  Country(id:153, title: 'MA', description: 'Morocco'),
  Country(id:154, title: 'MZ', description: 'Mozambique'),
  Country(id:155, title: 'MM', description: 'Myanmar (Burma)'),
  Country(id:156, title: 'NA', description: 'Namibia'),
  Country(id:157, title: 'NR', description: 'Nauru'),
  Country(id:158, title: 'NP', description: 'Nepal'),
  Country(id:159, title: 'NL', description: 'Netherlands'),
  Country(id:160, title: 'NC', description: 'New Caledonia'),
  Country(id:161, title: 'NZ', description: 'New Zealand'),
  Country(id:162, title: 'NI', description: 'Nicaragua'),
  Country(id:163, title: 'NE', description: 'Niger'),
  Country(id:164, title: 'NG', description: 'Nigeria'),
  Country(id:165, title: 'NU', description: 'Niue'),
  Country(id:166, title: 'NF', description: 'Norfolk Island'),
  Country(id:167, title: 'KP', description: 'North Korea'),
  Country(id:168, title: 'MP', description: 'Northern Mariana Islands'),
  Country(id:169, title: 'NO', description: 'Norway'),
  Country(id:170, title: 'OM', description: 'Oman'),
  Country(id:171, title: 'PK', description: 'Pakistan'),
  Country(id:172, title: 'PW', description: 'Palau'),
  Country(id:173, title: 'PS', description: 'Palestinian Territories'),
  Country(id:174, title: 'PA', description: 'Panama'),
  Country(id:175, title: 'PG', description: 'Papua New Guinea'),
  Country(id:176, title: 'PY', description: 'Paraguay'),
  Country(id:177, title: 'PE', description: 'Peru'),
  Country(id:178, title: 'PH', description: 'Philippines'),
  Country(id:179, title: 'PN', description: 'Pitcairn Islands'),
  Country(id:180, title: 'PL', description: 'Poland'),
  Country(id:181, title: 'PT', description: 'Portugal'),
  Country(id:182, title: 'PR', description: 'Puerto Rico'),
  Country(id:183, title: 'QA', description: 'Qatar'),
  Country(id:184, title: 'RE', description: 'Réunion'),
  Country(id:185, title: 'RO', description: 'Romania'),
  Country(id:186, title: 'RU', description: 'Russia'),
  Country(id:187, title: 'RW', description: 'Rwanda'),
  Country(id:188, title: 'WS', description: 'Samoa'),
  Country(id:189, title: 'SM', description: 'San Marino'),
  Country(id:190, title: 'ST', description: 'São Tomé & Príncipe'),
  Country(id:191, title: 'SA', description: 'Saudi Arabia'),
  Country(id:192, title: 'SN', description: 'Senegal'),
  Country(id:193, title: 'RS', description: 'Serbia'),
  Country(id:194, title: 'SC', description: 'Seychelles'),
  Country(id:195, title: 'SL', description: 'Sierra Leone'),
  Country(id:196, title: 'SG', description: 'Singapore'),
  Country(id:197, title: 'SX', description: 'Sint Maarten'),
  Country(id:198, title: 'SK', description: 'Slovakia'),
  Country(id:199, title: 'SI', description: 'Slovenia'),
  Country(id:200, title: 'SB', description: 'Solomon Islands'),
  Country(id:201, title: 'SO', description: 'Somalia'),
  Country(id:202, title: 'ZA', description: 'South Africa'),
  Country(id:203, title: 'GS', description: 'South Georgia & South Sandwich Islands'),
  Country(id:204, title: 'KR', description: 'South Korea'),
  Country(id:205, title: 'SS', description: 'South Sudan'),
  Country(id:206, title: 'ES', description: 'Spain'),
  Country(id:207, title: 'LK', description: 'Sri Lanka'),
  Country(id:208, title: 'BL', description: 'St. Barthélemy'),
  Country(id:209, title: 'SH', description: 'St. Helena'),
  Country(id:210, title: 'KN', description: 'St. Kitts & Nevis'),
  Country(id:211, title: 'LC', description: 'St. Lucia'),
  Country(id:212, title: 'MF', description: 'St. Martin'),
  Country(id:213, title: 'PM', description: 'St. Pierre & Miquelon'),
  Country(id:214, title: 'VC', description: 'St. Vincent & Grenadines'),
  Country(id:215, title: 'SD', description: 'Sudan'),
  Country(id:216, title: 'SR', description: 'Suriname'),
  Country(id:217, title: 'SJ', description: 'Svalbard & Jan Mayen'),
  Country(id:218, title: 'SZ', description: 'Swaziland'),
  Country(id:219, title: 'SE', description: 'Sweden'),
  Country(id:220, title: 'CH', description: 'Switzerland'),
  Country(id:221, title: 'SY', description: 'Syria'),
  Country(id:222, title: 'TW', description: 'Taiwan'),
  Country(id:223, title: 'TJ', description: 'Tajikistan'),
  Country(id:224, title: 'TZ', description: 'Tanzania'),
  Country(id:225, title: 'TH', description: 'Thailand'),
  Country(id:226, title: 'TL', description: 'Timor-Leste'),
  Country(id:227, title: 'TG', description: 'Togo'),
  Country(id:228, title: 'TK', description: 'Tokelau'),
  Country(id:229, title: 'TO', description: 'Tonga'),
  Country(id:230, title: 'TT', description: 'Trinidad & Tobago'),
  Country(id:231, title: 'TA', description: 'Tristan da Cunha'),
  Country(id:232, title: 'TN', description: 'Tunisia'),
  Country(id:233, title: 'TR', description: 'Turkey'),
  Country(id:234, title: 'TM', description: 'Turkmenistan'),
  Country(id:235, title: 'TC', description: 'Turks & Caicos Islands'),
  Country(id:236, title: 'TV', description: 'Tuvalu'),
  Country(id:237, title: 'UM', description: 'U.S. Outlying Islands'),
  Country(id:238, title: 'VI', description: 'U.S. Virgin Islands'),
  Country(id:239, title: 'UG', description: 'Uganda'),
  Country(id:240, title: 'UA', description: 'Ukraine'),
  Country(id:241, title: 'AE', description: 'United Arab Emirates'),
  Country(id:242, title: 'GB', description: 'United Kingdom'),
  Country(id:243, title: 'UN', description: 'United Nations'),
  Country(id:244, title: 'US', description: 'United States'),
  Country(id:245, title: 'UY', description: 'Uruguay'),
  Country(id:246, title: 'UZ', description: 'Uzbekistan'),
  Country(id:247, title: 'VU', description: 'Vanuatu'),
  Country(id:248, title: 'VA', description: 'Vatican City'),
  Country(id:249, title: 'VE', description: 'Venezuela'),
  Country(id:250, title: 'VN', description: 'Vietnam'),
  Country(id:251, title: 'WF', description: 'Wallis & Futuna'),
  Country(id:252, title: 'EH', description: 'Western Sahara'),
  Country(id:253, title: 'YE', description: 'Yemen'),
  Country(id:254, title: 'ZM', description: 'Zambia'),
  Country(id:255, title: 'ZW', description: 'Zimbabwe')
];